import { Router } from 'express';
import userRouter from './user.routes';
import doctorRouter from './doctor.routes';
import authRouter from './auth.routes';
import consultationPackageRouter from './consultationPackage.routes';
import consultationServiceRouter from './consultationService.routes';
import roomRouter from './room.routes';
import scheduleRouter from './schedule.routes';
import periodPackageRouter from './periodPackage.routes';
import dayPackageRouter from './dayPackage.routes';
import packageWeekRouter from './packageWeek.routes';
import blogRouter from './blog.routes';
import promotionRouter from './promotion.routes';
import specialtyRouter from './specialty.route';
import imageRouter from './image.routes';
import prescriptionRouter from './prescription.routes';
import medicalExaminationRoutes from './medicalExamination.routes';
import paymentRouter from './payment.routes';
import waitingMessageRouter from './waitingMessage.routes';
import chatRouter from './chat.route';
import medicationRouter from './medication.routes';
import medicineRouter from './medicine.routes';
import icdRouter from './icd.routes';
import { logMiddleware } from '../../middleware/log';

const router = Router();
router.use(logMiddleware);
router.use('/user', userRouter);
router.use('/doctor', doctorRouter);
router.use('/chat', chatRouter);
router.use('/auth', authRouter);
router.use('/consultation-package', consultationPackageRouter);
router.use('/consultation-service', consultationServiceRouter);
router.use('/room', roomRouter);
router.use('/schedule', scheduleRouter);
router.use('/period-package', periodPackageRouter);
router.use('/day-package', dayPackageRouter);
router.use('/package-week', packageWeekRouter);
router.use('/blog', blogRouter);
router.use('/promotion', promotionRouter);
router.use('/specialties', specialtyRouter);
router.use('/image', imageRouter);
router.use('/prescriptions', prescriptionRouter);
router.use('/medical-examinations', medicalExaminationRoutes);
router.use('/payment', paymentRouter);
router.use('/waiting-message', waitingMessageRouter);
router.use('/medications', medicationRouter);
router.use('/medicines', medicineRouter);
router.use('/icd', icdRouter);

export default router;
